name: microsoft_provider
description: Microsoft provider for TIKI
version: 0.0.3
homepage:

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_appauth: ^2.2.0
  httpp:
    git:
      url: https://github.com/tiki/httpp
      ref: 0.0.3
  logging: ^1.0.2
  provider: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.mytiki.microsoft_provider
        pluginClass: MicrosoftProviderPlugin
      ios:
        pluginClass: MicrosoftProviderPlugin
  assets:
    - res/images/